export const TEMPLATE_CONFIG = {
  recipientName: 'Faiza Saeed',
  senderName: 'Rehan',
  recipientAge: 21,
  yearsTogether: 0,
  distanceLabel: 'For my favourite cousin sister',
  senderCity: 'Lahore',
  recipientCity: 'Mianwali',
  openingLine: 'For the cousin who became one of my closest friends',
  openingNote: 'Some people are family by relation, but become special because of everything you grow through together.',
  letter: [
    'Dear Faiza,',
    'Happy 21st birthday to one of the most important people in my life. You are not just my cousin sister. Since childhood, you have been my best female cousin and someone I have always felt genuinely comfortable talking to.',
    'We have grown up with so many funny moments, random conversations, and memories that are difficult to explain to anyone else. You have been an emotional support for me in ways you probably do not even realise, and I am genuinely grateful for that.',
    'You are also one of those people who feels everything deeply. You can get angry, keep things to yourself, and if someone hurts you, you usually do not make a scene. You just become quiet and notice everything. But despite that, you have such a soft heart. You care about people, you love children, and most of all, you love your family more than you usually show.',
    'I honestly admire how brave and hardworking you are. You left home for hostel when you were still in class 5 because you wanted a better future. It has been around nine and a half years, and I know that behind all your strength, you still miss your family a lot. That part of your story makes me proud of you.',
    'I hope you become the successful engineer you dream of becoming, become completely independent, and achieve everything you work for. And I hope one day you are able to give your family all the happiness you have always wanted to give them.',
    'Keep being ambitious, hardworking, a little angry sometimes, and completely yourself. And please never forget that no matter how much life changes, you will always have a cousin in Lahore who is proud of you and will always be happy to have you in his life.',
    'And yes, keep listening to Karan Aujla like nothing else exists. 😂',
    'Happy 21st, Faiza. I hope this year brings you closer to every dream you are quietly working for.',
    'With lots of duas, respect, and countless childhood memories,',
    'Rehan'
  ],
  galleryImages: Array.from({ length: 16 }, (_, index) => `/demo/portrait-${(index % 4) + 1}.png`),
  memoryImages: ['/demo/portrait-1.png', '/demo/portrait-2.png', '/demo/portrait-3.png', '/demo/portrait-4.png'],
} as const;
